id: PF509153F
initial_creation_type: input
source_metadata:
  title: Jampal Dewe Nyima Series
  language: bo
  description: 'Texts by and about Khenchen Jampal Dewe Nyima (''jam dpal bde ba''i
    nyi ma) alias Gyurme Pendé Özer, the younger brother of Tertön Rangrik Dorje and
    teacher of Dudjom Rinpoche:'
  volume:
    f8ae4535ae88415d8df5304ec94f0b93:
      title: Prayer to the Lineage of Lumorab
      parent: Lineage Prayers
    7b06236fcb384687a6d76a0e7c6ff591:
      title: The Meaning of the Six Syllables of the King of Vidyā-Mantras, the Heroic
        Lord Mañjuśrī
      parent: Mantra
created_at: '2022-02-28T23:33:30.498920'
last_modified_at: '2022-02-28T23:33:30.498923'
